# -*- coding: utf-8 -*-
"""Simulation Mudaraba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U94pjcBKKY9EelbAeBO26eHuyqLQsItF
"""

import numpy as np
import os
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import warnings
warnings.filterwarnings('ignore')

plt.rcParams.update({
    'font.family': 'serif',
    'font.serif': ['Times New Roman', 'DejaVu Serif', 'Computer Modern Roman'],
    'font.size': 10,
    'mathtext.fontset': 'dejavuserif',
    'axes.titlesize': 12,
    'axes.titleweight': 'bold',
    'axes.labelsize': 11,
    'axes.labelweight': 'bold',
    'axes.linewidth': 0.8,
    'xtick.labelsize': 9,
    'ytick.labelsize': 9,
    'xtick.major.width': 0.6,
    'ytick.major.width': 0.6,
    'xtick.direction': 'in',
    'ytick.direction': 'in',
    'legend.fontsize': 9,
    'legend.framealpha': 0.95,
    'legend.edgecolor': '#AAAAAA',
    'legend.fancybox': False,
    'figure.dpi': 150,
    'savefig.dpi': 150,
    'savefig.bbox': 'tight',
    'savefig.pad_inches': 0.05,
    'savefig.facecolor': 'white',
    'savefig.edgecolor': 'none',
    'axes.grid': False,
    'lines.linewidth': 1.5,
    'lines.markersize': 6,
})

#  Markov states
states = [f'M{i}' for i in range(22)]
n_states = 22

# Transition rates λᵢ (i = 0..24), 25 transitions
lambda_rates = np.array([
    4, 6, 2, 5, 4, 3, 2, 4, 3, 2, 1, 5, 6, 4, 3, 5, 2, 3, 1, 2, 3, 4, 3, 5, 6
], dtype=float)

transition_desc = [
    "T₀:  M₀→M₁   Partnership application submitted",
    "T₁:  M₁→M₂   Blockchain recording (accepted)",
    "T₂:  M₁→M₀   Verification rejection → back to initial",
    "T₃:  M₂→M₃   Data verified, sent for review",
    "T₄:  M₃→M₄   Rabb al-mal reviews proposal",
    "T₅:  M₄→M₅   Negotiation agreed",
    "T₆:  M₄→M₃   Negotiation rejected → back to review",
    "T₇:  M₅→M₆   Draft agreement drawn up",
    "T₈:  M₆→M₇   Draft sent for DPS evaluation",
    "T₉:  M₇→M₈   DPS evaluation satisfactory",
    "T₁₀: M₇→M₆   DPS evaluation rejected → back to draft",
    "T₁₁: M₈→M₉   Final draft approved, agreement signed",
    "T₁₂: M₉→M₁₀  Agreement stored (blockchain)",
    "T₁₃: M₁₀→M₁₁ Funding request sent",
    "T₁₄: M₁₁→M₁₂ Funds disbursed",
    "T₁₅: M₁₂→M₁₃ Funds received by Mudarib",
    "T₁₆: M₁₃→M₁₄ Cattle purchased",
    "T₁₇: M₁₄→M₁₅ Cattle received, finances recorded",
    "T₁₈: M₁₅→M₁₆ Cattle husbandry & progress reports",
    "T₁₉: M₁₆→M₁₇ Reports sent to stakeholders",
    "T₂₀: M₁₇→M₁₈ DPS approves Sharia evaluation",
    "T₂₁: M₁₈→M₁₉ Final financial statements",
    "T₂₂: M₁₉→M₂₀ Final Sharia evaluation approved",
    "T₂₃: M₂₀→M₂₁ Profit sharing distributed",
    "T₂₄: M₂₁→M₀   Partnership concluded → return to initial",
]

state_descriptions = [
    "Initial state (idle)",
    "Partnership data is entered and accepted by the system",
    "The partnership data are verified as valid",
    "The Rabb al-mal reviews the partnership proposal",
    "Negotiations are underway",
    "Both parties agree to the negotiations",
    "A draft partnership agreement is drawn up",
    "The draft agreement is evaluated",
    "DPS evaluation satisfactory, final draft ready",
    "Both parties sign the agreement",
    "The agreement is stored in the system",
    "Funding request sent",
    "Funds disbursed by the Rabb al-Mal",
    "Funds received by Mudarib",
    "Cattle are purchased",
    "Project manager receives cattle, finances recorded",
    "Cattle husbandry and progress reports",
    "Progress reports sent to stakeholders",
    "DPS approves the Sharia evaluation",
    "Final financial statements and cattle reports",
    "Final Sharia evaluation is approved",
    "Profit sharing distributed, partnership concluded",
]

# Analytical coefficients (×P₀)
coefficients = [1, 1/2, 3/5, 5/4, 1, 3/4, 3/2, 3/2, 3/5, 1/2, 3/4, 1, 3/5, 3/2, 1, 3, 3/2, 1, 3/4, 1, 3/5, 1/2]
fractions = ["20/448", "10/448", "12/448", "25/448", "20/448", "15/448", "30/448", "30/448", "12/448", "10/448", "15/448", "20/448", "12/448", "30/448", "20/448", "60/448", "30/448", "20/448", "15/448", "20/448", "12/448", "10/448"]

phase_labels = {
    'Pre-Contract': list(range(0, 9)),
    'Contract Execution': list(range(9, 17)),
    'Settlement': list(range(17, 22)),
}

phase_percentages = {
    'Pre-Contract': 38.84,
    'Contract Execution': 43.97,
    'Settlement': 17.19
}

# MATRIX Q
def build_generator_matrix(lam):
    """

    Transition structure from the Markov chain:
      M₀  →  M₁  (λ₀=4)
      M₁  →  M₂  (λ₁=6)   |  M₁ → M₀ (λ₂=2)     [rejection: verification]
      M₂  →  M₃  (λ₃=5)
      M₃  →  M₄  (λ₄=4)
      M₄  →  M₅  (λ₅=3)   |  M₄ → M₃ (λ₆=2)     [rejection: negotiation]
      M₅  →  M₆  (λ₇=4)
      M₆  →  M₇  (λ₈=3)
      M₇  →  M₈  (λ₉=2)   |  M₇ → M₆ (λ₁₀=1)    [rejection: DPS evaluation]
      M₈  →  M₉  (λ₁₁=5)
      M₉  →  M₁₀ (λ₁₂=6)
      M₁₀ →  M₁₁ (λ₁₃=4)
      M₁₁ →  M₁₂ (λ₁₄=3)
      M₁₂ →  M₁₃ (λ₁₅=5)
      M₁₃ →  M₁₄ (λ₁₆=2)
      M₁₄ →  M₁₅ (λ₁₇=3)
      M₁₅ →  M₁₆ (λ₁₈=1)
      M₁₆ →  M₁₇ (λ₁₉=2)
      M₁₇ →  M₁₈ (λ₂₀=3)
      M₁₈ →  M₁₉ (λ₂₁=4)
      M₁₉ →  M₂₀ (λ₂₂=3)
      M₂₀ →  M₂₁ (λ₂₃=5)
      M₂₁ →  M₀  (λ₂₄=6)
    """
    Q = np.zeros((n_states, n_states))

    transitions = [
        (0,  1,  lam[0]),   (1,  2,  lam[1]),   (2,  3,  lam[3]),
        (3,  4,  lam[4]),   (4,  5,  lam[5]),   (5,  6,  lam[7]),
        (6,  7,  lam[8]),   (7,  8,  lam[9]),   (8,  9,  lam[11]),
        (9,  10, lam[12]),  (10, 11, lam[13]),  (11, 12, lam[14]),
        (12, 13, lam[15]),  (13, 14, lam[16]),  (14, 15, lam[17]),
        (15, 16, lam[18]),  (16, 17, lam[19]),  (17, 18, lam[20]),
        (18, 19, lam[21]),  (19, 20, lam[22]),  (20, 21, lam[23]),
        (21, 0,  lam[24]),
    ]

    rejections = [
        (1, 0, lam[2]),    # M₁→M₀
        (4, 3, lam[6]),    # M₄→M₃
        (7, 6, lam[10]),   # M₇→M₆
    ]

    for (i, j, rate) in transitions + rejections:
        Q[i, j] = rate

    for i in range(n_states):
        Q[i, i] = -np.sum(Q[i, :])

    return Q

# ANALYTICAL SOLUTION
def analytical_solution():
    coeff = np.array(coefficients)
    P0 = 1.0 / np.sum(coeff)
    probs = coeff * P0
    return probs

# NUMERICAL SOLUTION (NumPy linalg)
def numerical_solution(Q):
    A = Q.T.copy()
    A[-1, :] = 1.0
    b = np.zeros(n_states)
    b[-1] = 1.0
    pi = np.linalg.solve(A, b)
    return pi

# SPN MONTE CARLO SIMULATION
BUFFER_RATES = [5.0, 4.0, 3.0]
N_TOTAL = 25
BUF1, BUF2, BUF3 = 22, 23, 24


def build_Q_spn(lam, buf_rates=BUFFER_RATES):
    Q = np.zeros((N_TOTAL, N_TOTAL))

    forward = [
        (0,1,lam[0]),   (1,2,lam[1]),   (2,3,lam[3]),   (3,4,lam[4]),
        (4,5,lam[5]),   (5,6,lam[7]),   (6,7,lam[8]),   (7,8,lam[9]),
        (8,9,lam[11]),  (9,10,lam[12]), (10,11,lam[13]), (11,12,lam[14]),
        (12,13,lam[15]), (13,14,lam[16]), (14,15,lam[17]), (15,16,lam[18]),
        (16,17,lam[19]), (17,18,lam[20]), (18,19,lam[21]), (19,20,lam[22]),
        (20,21,lam[23]), (21,0,lam[24]),
    ]

    rejections = [
        (1, BUF1, lam[2]),
        (4, BUF2, lam[6]),
        (7, BUF3, lam[10]),
    ]

    returns = [
        (BUF1, 0, buf_rates[0]),
        (BUF2, 3, buf_rates[1]),
        (BUF3, 6, buf_rates[2]),
    ]

    for (i, j, rate) in forward + rejections + returns:
        Q[i, j] = rate

    for i in range(N_TOTAL):
        Q[i, i] = -np.sum(Q[i, :])

    return Q


def monte_carlo_simulation(Q_22state, n_firings=2000, n_replications=10, seed=42):
    rng = np.random.default_rng(seed)
    Q_spn = build_Q_spn(lambda_rates)
    all_probs = np.zeros((n_replications, n_states))

    for rep in range(n_replications):
        time_in_state = np.zeros(N_TOTAL)
        current_state = 0

        for _ in range(n_firings):
            exit_rate = -Q_spn[current_state, current_state]
            if exit_rate <= 0:
                break
            sojourn_time = rng.exponential(1.0 / exit_rate)
            time_in_state[current_state] += sojourn_time
            outgoing_rates = Q_spn[current_state, :].copy()
            outgoing_rates[current_state] = 0
            outgoing_rates = np.maximum(outgoing_rates, 0)
            total_out = np.sum(outgoing_rates)
            if total_out <= 0:
                break
            probs = outgoing_rates / total_out
            current_state = rng.choice(N_TOTAL, p=probs)

        total_time = np.sum(time_in_state)
        if total_time > 0:
            all_25_probs = time_in_state / total_time
            all_probs[rep, :] = all_25_probs[:n_states]

    mean_probs = np.mean(all_probs, axis=0)
    std_probs = np.std(all_probs, axis=0)
    return mean_probs, std_probs, all_probs

state_labels_fig = []
for _i in range(22):
    _sub = ''.join([chr(0x2080 + int(d)) for d in str(_i)])
    state_labels_fig.append(f'M{_sub}')


def plot_figure(ana, num, mc_mean, mc_std, save_dir):
    fig, ax = plt.subplots(figsize=(7.09, 3.54))

    x = np.arange(n_states)
    width = 0.24

    c_ana = '#1B3A5C'
    c_num = '#4A90C4'
    c_mc  = '#C44E52'

    ax.bar(x - width, ana, width,
           label='Analytical (PQ = 0)',
           color=c_ana, edgecolor='white', linewidth=0.2, zorder=3)
    ax.bar(x, num, width,
           label='Numerical (NumPy linalg)',
           color=c_num, edgecolor='white', linewidth=0.2, zorder=3)
    ax.bar(x + width, mc_mean, width,
           label='SPN Simulation (Monte Carlo)',
           color=c_mc, edgecolor='white', linewidth=0.2, zorder=3,
           yerr=mc_std, capsize=1.5,
           error_kw={'linewidth': 0.6, 'color': '#333333', 'capthick': 0.5})

    ax.set_xlabel('Markov State', fontsize=11, fontweight='bold')
    ax.set_ylabel('Steady-State Probability P(M$_i$)', fontsize=11, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(state_labels_fig, fontsize=8)
    ax.set_ylim(0, 0.16)
    ax.yaxis.set_major_formatter(mticker.FormatStrFormatter('%.2f'))

    ax.yaxis.grid(True, linestyle='-', alpha=0.15, linewidth=0.4, zorder=0)
    ax.set_axisbelow(True)

    leg = ax.legend(loc='upper left', framealpha=0.95, edgecolor='#BBBBBB',
                    fontsize=8.5, borderpad=0.6, handlelength=1.5)
    leg.get_frame().set_linewidth(0.4)

    m15 = 15
    peak = max(ana[m15], num[m15], mc_mean[m15] + mc_std[m15])
    ax.annotate('(M$_{15}$)', xy=(m15 + width, peak + 0.004),
                fontsize=10, fontweight='bold', color='#CC0000',
                ha='center', va='bottom')

    txt = (f'ΣP(M$_i$): Ana={np.sum(ana):.4f}, '
           f'Num={np.sum(num):.4f}, Sim={np.sum(mc_mean):.4f}')
    ax.text(0.98, 0.97, txt, transform=ax.transAxes,
            fontsize=7.5, ha='right', va='top',
            bbox=dict(boxstyle='round,pad=0.35', facecolor='white',
                      edgecolor='#AAAAAA', linewidth=0.4, alpha=0.95))

    for sp in ['top', 'right']:
        ax.spines[sp].set_visible(False)
    for sp in ['left', 'bottom']:
        ax.spines[sp].set_linewidth(0.5)

    plt.tight_layout(pad=0.3)

    # Display the plot directly
    plt.show()

    # Save the plot to files
    base = os.path.join(save_dir, 'Figure_Steady_State_Comparison')
    fig.savefig(f'{base}.png',  dpi=FIGURE_DPI, bbox_inches='tight', facecolor='white')
    fig.savefig(f'{base}.pdf',  bbox_inches='tight', facecolor='white')
    fig.savefig(f'{base}.tiff', dpi=FIGURE_DPI, bbox_inches='tight', facecolor='white',
                pil_kwargs={'compression': 'tiff_lzw'})

    print(f"  ✅ Figure saved ({FIGURE_DPI} DPI):")
    print(f"     PNG:  {base}.png")
    return fig

FIGURE_DPI = 600
save_dir = 'figures'
os.makedirs(save_dir, exist_ok=True)

# Calculate analytical solution
ana_probs = analytical_solution()

# Build generator matrix and calculate numerical solution
Q_matrix = build_generator_matrix(lambda_rates)
num_probs = numerical_solution(Q_matrix)

# Run Monte Carlo simulation
mc_mean, mc_std, _ = monte_carlo_simulation(Q_matrix)

# Plot and save the figure
from IPython.display import display

# Memanggil fungsi dengan nama baru: plot_figure
fig_output = plot_figure(ana_probs, num_probs, mc_mean, mc_std, save_dir)
display(fig_output)

# SENSITIVITY ANALYSIS
def sensitivity_analysis(lambda_base, lambda18_values):
    results = {}
    for l18 in lambda18_values:
        lam = lambda_base.copy()
        lam[18] = l18
        Q = build_generator_matrix(lam)
        pi = numerical_solution(Q)
        results[l18] = pi
    return results

def plot_figure6(sens_results, lambda18_values, save_dir):
    """Figure 6: Sensitivity Analysis — uses SAME pre-computed data."""
    l18_vals = np.array(lambda18_values)

    p15 = np.array([sens_results[l][15] * 100 for l in l18_vals])
    p3  = np.array([sens_results[l][3]  * 100 for l in l18_vals])
    p6  = np.array([sens_results[l][6]  * 100 for l in l18_vals])
    p13 = np.array([sens_results[l][13] * 100 for l in l18_vals])
    p16 = np.array([sens_results[l][16] * 100 for l in l18_vals])

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(7.09, 3.54))
    c_bn = '#8B1A1A'

    # (a) Bottleneck Probability 
    ax1.plot(l18_vals, p15, 'o-', color=c_bn,
             markerfacecolor='white', markeredgecolor=c_bn,
             markeredgewidth=1.4, markersize=6.5, linewidth=1.8,
             label='P(M$_{15}$)')
    ax1.fill_between(l18_vals, 0, p15, alpha=0.10, color=c_bn)

    bl_idx = np.where(l18_vals == 1.0)[0][0]
    bl_val = p15[bl_idx]
    ax1.axhline(y=bl_val, color='gray', ls='--', lw=0.8, alpha=0.6,
                label=f'Baseline (λ₁₈=1): {bl_val:.2f}%')

    op_idx = np.where(l18_vals == 3.0)[0][0]
    op_val = p15[op_idx]
    ax1.axvline(x=3.0, color='#00A86B', ls=':', lw=1.6, alpha=0.75,
                label='Optimal λ₁₈ = 3.0')
    ax1.annotate(f'{op_val:.2f}%', xy=(3.0, op_val),
                 xytext=(3.55, op_val + 2.2),
                 fontsize=9.5, fontweight='bold', color='#00A86B',
                 arrowprops=dict(arrowstyle='->', color='#00A86B', lw=1.2),
                 ha='left')

    ax1.set_xlabel('λ$_{18}$ (Maintenance Process Rate)',
                   fontsize=10, fontweight='bold')
    ax1.set_ylabel('P(M$_{15}$) [%]', fontsize=10, fontweight='bold')
    ax1.set_title('(a) Bottleneck Probability vs λ$_{18}$',
                  fontsize=11, fontweight='bold')
    ax1.legend(loc='upper right', fontsize=8, framealpha=0.95,
               edgecolor='#BBBBBB')
    ax1.set_xlim(0.3, 5.2)
    ax1.set_ylim(0, max(p15) * 1.1)
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)
    ax1.yaxis.grid(True, ls='-', alpha=0.15, lw=0.4)

    # (b) Probability Redistribution
    mk = dict(markerfacecolor='white', markeredgewidth=1.3, markersize=6)

    ax2.plot(l18_vals, p3,  's-', color='#2171B5', **mk,
             markeredgecolor='#2171B5', lw=1.5,
             label='M$_3$ (Negotiation Stage)')
    ax2.plot(l18_vals, p6,  'D-', color='#7B2D8E', **mk,
             markeredgecolor='#7B2D8E', lw=1.5,
             label='M$_6$ (Draft Agreement)')
    ax2.plot(l18_vals, p13, '^-', color='#E6A817', **mk,
             markeredgecolor='#E6A817', lw=1.5,
             label='M$_{13}$ (Fund Received)')
    ax2.plot(l18_vals, p15, 'o-', color=c_bn,
             markerfacecolor=c_bn, markeredgecolor=c_bn,
             markersize=6, lw=2,
             label='M$_{15}$ (Maintenance — Bottleneck)')
    ax2.plot(l18_vals, p16, 'v-', color='#2CA02C', **mk,
             markeredgecolor='#2CA02C', lw=1.5,
             label='M$_{16}$ (Maintenance Report)')

    ax2.axvline(x=3.0, color='gray', ls=':', lw=0.8, alpha=0.4)

    ax2.set_xlabel('λ$_{18}$ (Maintenance Process Rate)',
                   fontsize=10, fontweight='bold')
    ax2.set_ylabel('Steady-State Probability [%]',
                   fontsize=10, fontweight='bold')
    ax2.set_title('(b) Probability Redistribution Across States',
                  fontsize=11, fontweight='bold')
    ax2.legend(loc='upper right', fontsize=8, framealpha=0.95,
               edgecolor='#BBBBBB')
    ax2.set_xlim(0.3, 5.2)
    ax2.set_ylim(0, max(p15) * 1.1)
    ax2.spines['top'].set_visible(False)
    ax2.spines['right'].set_visible(False)
    ax2.yaxis.grid(True, ls='-', alpha=0.15, lw=0.4)

    plt.tight_layout(w_pad=2.5, pad=0.3)

    base = os.path.join(save_dir, 'Figure6_Sensitivity_Analysis')
    fig.savefig(f'{base}.png',  dpi=FIGURE_DPI, bbox_inches='tight', facecolor='white')
    fig.savefig(f'{base}.pdf',  bbox_inches='tight', facecolor='white')
    fig.savefig(f'{base}.tiff', dpi=FIGURE_DPI, bbox_inches='tight', facecolor='white',
                pil_kwargs={'compression': 'tiff_lzw'})

    print(f"  ✅ Figure  saved ({FIGURE_DPI} DPI):")

    plt.close(fig)

def plot_figure1_improved(sens_results, lambda18_values, save_dir):
    l18_vals = np.array(lambda18_values)
    p15 = np.array([sens_results[l][15] * 100 for l in l18_vals])
    p3  = np.array([sens_results[l][3]  * 100 for l in l18_vals])
    p6  = np.array([sens_results[l][6]  * 100 for l in l18_vals])
    p13 = np.array([sens_results[l][13] * 100 for l in l18_vals])
    p16 = np.array([sens_results[l][16] * 100 for l in l18_vals])

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    c_bn = '#8B1A1A'

    # Subplot (a) Probabilitas Bottleneck
    ax1.plot(l18_vals, p15, 'o-', color=c_bn, markerfacecolor='white', markeredgewidth=1.5, markersize=7, linewidth=2, label='P(M$_{15}$)')
    ax1.fill_between(l18_vals, 0, p15, alpha=0.1, color=c_bn)

    bl_val = p15[np.where(l18_vals == 1.0)[0][0]]
    ax1.axhline(y=bl_val, color='gray', ls='--', lw=0.8, alpha=0.6, label=f'Baseline (λ₁₈=1): {bl_val:.2f}%')

    op_idx = np.where(l18_vals == 3.0)[0][0]
    op_val = p15[op_idx]
    ax1.axvline(x=3.0, color='#00A86B', ls=':', lw=1.6, alpha=0.75, label='Optimal λ₁₈ = 3.0')
    ax1.annotate(f'{op_val:.2f}%', xy=(3.0, op_val), xytext=(3.5, op_val + 2),
                 arrowprops=dict(arrowstyle='->', color='#00A86B'), color='#00A86B', fontweight='bold')

    ax1.set_xlabel('λ$_{18}$ (Laju Proses Pemeliharaan)', fontweight='bold')
    ax1.set_ylabel('P(M$_{15}$) [%]', fontweight='bold')
    ax1.set_title('(a) Probabilitas Bottleneck vs λ$_{18}$', fontweight='bold')
    ax1.legend(fontsize=9)
    ax1.grid(True, alpha=0.2)

    # Subplot (b) Redistribusi Probabilitas
    mk = dict(markerfacecolor='white', markeredgewidth=1.3, markersize=6)
    ax2.plot(l18_vals, p3,  's-', label='M$_3$ (Tahap Negosiasi)', **mk)
    ax2.plot(l18_vals, p6,  'D-', label='M$_6$ (Draft Perjanjian)', **mk)
    ax2.plot(l18_vals, p13, '^-', label='M$_{13}$ (Dana Diterima)', **mk)
    ax2.plot(l18_vals, p15, 'o-', color=c_bn, lw=2, label='M$_{15}$ (Bottleneck)')
    ax2.plot(l18_vals, p16, 'v-', label='M$_{16}$ (Laporan Pemeliharaan)', **mk)

    ax2.set_xlabel('λ$_{18}$ (Laju Proses Pemeliharaan)', fontweight='bold')
    ax2.set_ylabel('Steady-State Probability [%]', fontweight='bold')
    ax2.set_title('(b) Redistribusi Probabilitas antar State', fontweight='bold')
    ax2.legend(fontsize=8)
    ax2.grid(True, alpha=0.2)

    plt.tight_layout()
    base = os.path.join(save_dir, 'Figure1_Sensitivity_Analysis')
    fig.savefig(f'{base}.png', dpi=600, bbox_inches='tight')
    plt.show()
    return fig

# Menjalankan analisis
l18_test_values = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0]
sens_data = sensitivity_analysis(lambda_rates, l18_test_values)
plot_figure1_improved(sens_data, l18_test_values, 'figures')

# DISPLAY FUNCTIONS - Updated with DPS term
def print_header(title, width=80):
    print("\n" + "═" * width)
    print(f"  {title}")
    print("═" * width)

def print_subheader(title, width=80):
    print(f"\n  ── {title} ──")

def display_transition_rates():
    print_header("TABLE 1: TRANSITION RATES (λᵢ)")
    print(f"\n  {'Index':<8} {'λᵢ':>6}  {'Description'}")
    print("  " + "─" * 70)
    for i, (rate, desc) in enumerate(zip(lambda_rates, transition_desc)):
        mark = " ◄ BOTTLENECK" if i == 18 else ""
        print(f"  λ{i:<5}  {rate:>5.1f}  {desc}{mark}")
    print(f"\n  Total transitions: {len(lambda_rates)}")
    print(f"  Rejection paths:  3 (λ₂: M₁→M₀, λ₆: M₄→M₃, λ₁₀: M₇→M₆)")

def display_steady_state(ana, num, mc_mean, mc_std):
    print_header("TABLE 2: STEADY-STATE PROBABILITIES P(Mᵢ)")
    print(f"\n  {'State':<6} {'Coeff':>8} {'Fraction':>10} "
          f"{'Analytical':>12} {'Numerical':>12} {'MC Mean':>12} "
          f"{'MC Std':>10} {'Description'}")
    print("  " + "─" * 120)
    for i in range(n_states):
        tag = " ◄◄◄ BOTTLENECK" if i == 15 else ""
        print(f"  M{i:<4} {coefficients[i]:>8.4f} {fractions[i]:>10} "
              f"{ana[i]:>12.6f} {num[i]:>12.6f} {mc_mean[i]:>12.6f} "
              f"{mc_std[i]:>10.6f}  {state_descriptions[i]}{tag}")
    print("  " + "─" * 120)
    print(f"  {'SUM':<6} {sum(coefficients):>8.4f} {'':>10} "
          f"{np.sum(ana):>12.6f} {np.sum(num):>12.6f} {np.sum(mc_mean):>12.4f}")
    print_subheader("Error Analysis")
    print(f"  Max |Analytical − Numerical| = {np.max(np.abs(ana - num)):.2e}")
    print(f"  Max |Analytical − MC|        = {np.max(np.abs(ana - mc_mean)):.4f}")
    print_subheader("Bottleneck Identification")
    bn_idx = np.argmax(ana)
    print(f"  Bottleneck state: M{bn_idx} (P = {ana[bn_idx]:.6f} = {ana[bn_idx]*100:.2f}%)")
    print(f"  → Cattle maintenance is the system's primary performance bottleneck")

def display_phases(ana):
    print_header("TABLE 6: PHASE DISTRIBUTION ANALYSIS")
    print(f"\n  {'Phase':<24} {'States':<18} {'∑P(Mᵢ)':>10} "
          f"{'Percentage':>12} {'Paper %':>10} {'Description'}")
    print("  " + "─" * 100)
    for phase, state_indices in phase_labels.items():
        phase_sum = np.sum(ana[state_indices])
        pct = phase_sum * 100
        paper_pct = phase_percentages[phase]
        s_range = f"M{state_indices[0]}–M{state_indices[-1]}"
        desc = {
            'Pre-Contract': 'Proposal submission, verification, negotiation, DPS evaluation',
            'Contract Execution': 'Agreement signing, funding, cattle purchase, maintenance',
            'Settlement': 'Final reporting, Sharia evaluation, profit sharing',
        }
        print(f"  {phase:<24} {s_range:<18} {phase_sum:>10.6f} "
              f"{pct:>11.2f}% {paper_pct:>9.2f}%  {desc[phase]}")
    print("  " + "─" * 100)
    print(f"  {'TOTAL':<24} {'M0–M21':<18} {np.sum(ana):>10.6f} "
          f"{np.sum(ana)*100:>11.2f}%")

# Memanggil fungsi tampilan untuk tabel hasil
display_transition_rates()
display_steady_state(ana_probs, num_probs, mc_mean, mc_std)
display_phases(ana_probs)

# Menampilkan Figure 1 (Analisis Sensitivitas)
plot_figure1_improved(sens_data, l18_test_values, 'figures')
